BINDING_PULL_TANK = "一键拉怪";
BINDING_TOP_TANK = "一键嘲讽/惩戒痛击/挑战怒吼";

SKILL_FUCHOU = "复仇";
SKILL_DUNPAIMENGJI = "盾牌猛击";
SKILL_YINYONGDAJI = "英勇打击";
SKILL_DUNPAIGEDANG = "盾牌格挡";
SKILL_POJIAGONGJI = "破甲攻击";
SKILL_CHAOFENG = "嘲讽";
SKILL_TIAOZHANNUHOU = "挑战怒吼";
SKILL_CHENGJIETONGJI = "惩戒痛击";

